version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: "Create CloudFormation Stack"
          command: |
            aws cloudformation create-stack \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --template-body file://IaC/template.yml \
            --parameters file://IaC/template-parameters.json \
            --region us-east-1


workflows:
  myWorkFlow:
    jobs:
      - create-infrastructure
