version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: "Create CloudFormation Stack"
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \  
            --parameters file://template-parameters.json \
            --region us-east-1

workflows:
  myWorkFlow:
    jobs:
      - create-infrastructure
